name: Deploy Introduction Site
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # v3からv4へ更新
      - name: Setup Pages
        uses: actions/configure-pages@v4 # 最新版へ
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3 # v1(内部でv3を使用)からv3へ更新
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 # v1からv4へ更新
